FROM nikolaik/python-nodejs:python3.11-nodejs20-bullseye

WORKDIR /opt/pydeps

ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN mkdir -p /.cache && chmod -R 777 /.cache
