#ifndef PINS_H
#define PINS_H

// Define a bunch of names depending on the active build target

#ifdef STM32F207xx

#define ESP_USART USART6
#define ESP_USART_Port GPIOG
#define ESP_USART_TX LL_GPIO_PIN_14
#define ESP_USART_RX LL_GPIO_PIN_9

#define ESP_USART_IRQ_NAME USART6_IRQn
#define ESP_USART_IRQ_HANDLER USART6_IRQHandler

#define SIGN_DATA_Port GPIOD
#define SIGN_GPIO_PERIPH LL_AHB1_GRP1_PERIPH_GPIOD

#define UART_DMA DMA2
#define UART_DMA_TX_Stream LL_DMA_STREAM_7
#define UART_DMA_RX_Stream LL_DMA_STREAM_1
#define UART_DMA_Channel LL_DMA_CHANNEL_5

#define UART_DMA_PERIPH LL_AHB1_GRP1_PERIPH_DMA2
#define UART_GPIO_PERIPH LL_AHB1_GRP1_PERIPH_GPIOG
#define UART_UART_PERIPH LL_APB2_GRP1_PERIPH_USART6
#define UART_ENABLE_CALL LL_APB2_GRP1_EnableClock
#define UART_Af LL_GPIO_AF_8

#define NVIC_SRV_RX_IRQ_NAME DMA2_Stream1_IRQn
#define NVIC_SRV_TX_IRQ_NAME DMA2_Stream7_IRQn

#define NVIC_SRV_RX_IRQ_HANDLER DMA2_Stream1_IRQHandler
#define NVIC_SRV_TX_IRQ_HANDLER DMA2_Stream7_IRQHandler

#define NVIC_SRV_RX_ACTV LL_DMA_IsActiveFlag_TC1
#define NVIC_SRV_RXE_ACTV LL_DMA_IsActiveFlag_TE1
#define NVIC_SRV_TX_ACTV LL_DMA_IsActiveFlag_TC7

#define NVIC_SRV_RX_CLRF LL_DMA_ClearFlag_TC1
#define NVIC_SRV_RXE_CLRF LL_DMA_ClearFlag_TE1
#define NVIC_SRV_TX_CLRF LL_DMA_ClearFlag_TC7

#endif

#ifdef STM32F205xx

#define ESP_USART USART2
#define ESP_USART_Port GPIOA
#define ESP_USART_TX LL_GPIO_PIN_2
#define ESP_USART_RX LL_GPIO_PIN_3

#define ESP_USART_IRQ_NAME USART2_IRQn
#define ESP_USART_IRQ_HANDLER USART2_IRQHandler

#define SIGN_DATA_Port GPIOC
#define SIGN_GPIO_PERIPH LL_AHB1_GRP1_PERIPH_GPIOC

#define UART_DMA DMA1
#define UART_DMA_TX_Stream LL_DMA_STREAM_6
#define UART_DMA_RX_Stream LL_DMA_STREAM_5
#define UART_DMA_Channel LL_DMA_CHANNEL_4

#define UART_DMA_PERIPH LL_AHB1_GRP1_PERIPH_DMA1
#define UART_GPIO_PERIPH LL_AHB1_GRP1_PERIPH_GPIOA
#define UART_UART_PERIPH LL_APB1_GRP1_PERIPH_USART2
#define UART_ENABLE_CALL LL_APB1_GRP1_EnableClock
#define UART_Af LL_GPIO_AF_7

#define NVIC_SRV_RX_IRQ_NAME DMA1_Stream5_IRQn
#define NVIC_SRV_TX_IRQ_NAME DMA1_Stream6_IRQn

#define NVIC_SRV_RX_IRQ_HANDLER DMA1_Stream5_IRQHandler
#define NVIC_SRV_TX_IRQ_HANDLER DMA1_Stream6_IRQHandler

#define NVIC_SRV_RX_ACTV LL_DMA_IsActiveFlag_TC5
#define NVIC_SRV_RXE_ACTV LL_DMA_IsActiveFlag_TE5
#define NVIC_SRV_TX_ACTV LL_DMA_IsActiveFlag_TC6

#define NVIC_SRV_RX_CLRF LL_DMA_ClearFlag_TC5
#define NVIC_SRV_RXE_CLRF LL_DMA_ClearFlag_TE5
#define NVIC_SRV_TX_CLRF LL_DMA_ClearFlag_TC6

#endif

#endif
