#ifndef FONT_DEJAVUSANS_8_H
#define FONT_DEJAVUSANS_8_H

namespace font::dejavusans_8 {
extern const void * const info[4]; // metrics, data, pointer to kern_size, kerning
}

// generated by fnter w/ /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

#endif
