#ifndef FONT_LATO_BOLD_15_H
#define FONT_LATO_BOLD_15_H

namespace font::lato_bold_15 {
extern const void * const info[4]; // metrics, data, pointer to kern_size, kerning
}

// generated by fnter w/ /usr/share/fonts/truetype/lato/Lato-Bold.ttf

#endif
