#ifndef FONT_LCDPIXEL_6_H
#define FONT_LCDPIXEL_6_H

namespace font::lcdpixel_6 {
extern const void * const info[4]; // metrics, data, pointer to kern_size, kerning
}

// generated by fnter w/ /home/matthew/projects/stm32-leds/bmap/testfnt/build/lcdpixel.bdf

#endif
