#ifndef FONT_TAHOMA_9_H
#define FONT_TAHOMA_9_H

namespace font::tahoma_9 {
extern const void * const info[4]; // metrics, data, pointer to kern_size, kerning
}

// generated by fnter w/ /home/matthew/Downloads/tahoma.ttf

#endif
