#ifndef FONT_VERA_7_H
#define FONT_VERA_7_H

namespace font::vera_7 {
extern const void * const info[4]; // metrics, data, pointer to kern_size, kerning
}

// generated by fnter w/ /usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf

#endif
